/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishedDate' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface _SERVICE {
  'createPost' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      Array<string>,
      boolean,
    ],
    undefined
  >,
  'deletePost' : ActorMethod<[string], undefined>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getPublishedPosts' : ActorMethod<[], Array<BlogPost>>,
  'updatePost' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      Array<string>,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];