/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ImageFit = IDL.Variant({
  'contain' : IDL.Null,
  'cover' : IDL.Null,
  'original' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const ImageMeta = IDL.Record({
  'fit' : ImageFit,
  'blob' : ExternalBlob,
  'size' : ImageSize,
});
export const InlineImage = IDL.Record({
  'image' : ImageMeta,
  'position' : IDL.Nat,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BlogPostView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'updatedDate' : IDL.Opt(IDL.Int),
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'inlineImages' : IDL.Vec(InlineImage),
  'publishedDate' : IDL.Opt(IDL.Int),
  'featuredImage' : IDL.Opt(ImageMeta),
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'createdDate' : IDL.Int,
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'publicationDate' : IDL.Opt(IDL.Int),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'comments' : IDL.Vec(Comment),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canCallerAccessAdminSection' : IDL.Func([], [IDL.Bool], ['query']),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(ImageMeta),
        IDL.Vec(InlineImage),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPostView)], ['query']),
  'getAllPostsForAdminPage' : IDL.Func([], [IDL.Vec(BlogPostView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPostView)], ['query']),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPostView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPublishedState' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Bool],
      [],
    ),
  'updatePost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(ImageMeta),
        IDL.Vec(InlineImage),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ImageFit = IDL.Variant({
    'contain' : IDL.Null,
    'cover' : IDL.Null,
    'original' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ImageMeta = IDL.Record({
    'fit' : ImageFit,
    'blob' : ExternalBlob,
    'size' : ImageSize,
  });
  const InlineImage = IDL.Record({ 'image' : ImageMeta, 'position' : IDL.Nat });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BlogPostView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'updatedDate' : IDL.Opt(IDL.Int),
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'inlineImages' : IDL.Vec(InlineImage),
    'publishedDate' : IDL.Opt(IDL.Int),
    'featuredImage' : IDL.Opt(ImageMeta),
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'createdDate' : IDL.Int,
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'publicationDate' : IDL.Opt(IDL.Int),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'comments' : IDL.Vec(Comment),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canCallerAccessAdminSection' : IDL.Func([], [IDL.Bool], ['query']),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(ImageMeta),
          IDL.Vec(InlineImage),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPostView)], ['query']),
    'getAllPostsForAdminPage' : IDL.Func(
        [],
        [IDL.Vec(BlogPostView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPostView)], ['query']),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPostView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPublishedState' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Bool],
        [],
      ),
    'updatePost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(ImageMeta),
          IDL.Vec(InlineImage),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };